description: >
  This the Drupal Stand CI.
docker:
  - image: 'mobomo/drupalstand-ci:<< parameters.tag >>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific mobomo/drupalstand-ci image variant:
      https://hub.docker.com/r/mobomo/drupalstand-ci/tags
    type: string
